### ISSUE TITLE
SECURITY.md: Missing details about reporting process in SAP Trust Center

### ISSUE THREAD

**Issue by Ein-Tim** [kulturpass-de/kulturpass-documentation#1]
The [SECURITY.md](https://github.com/kulturpass-de/kulturpass-documentation/blob/main/SECURITY.md) document states:

"**Please do not report security vulnerabilities through public GitHub issues.**

Instead, please report them via the SAP Trust Center at https://www.sap.com/about/trust-center/security/incident-management.html."

However, it is not clear which product one should select at the "Report a Security Vulnerability" form, located here: https://vulnerability-form.cfapps.sap.hana.ondemand.com/#/

There is no option "Kulturpass".

**Comment by christianneu** [comment]
We are currently preparing this and should be available shortly. I will update the file with the proper id when it's there. Thanks for pointing out anyway. :-)

**Comment by Ein-Tim** [comment]
@christianneu Any update reg. this? There's still no option "KulturPass"

**Comment by christianneu** [comment]
This part is still under discussion. I will get back to you soon.
In the meantime, security incidents still can be sent encrypted to [secure@sap.com](mailto:secure@sap.com).
