### ISSUE TITLE
Why does the app check "Pseudonym", "Gülitg bis" & "Geburtsort"?

### ISSUE THREAD

**Issue by Ein-Tim** [kulturpass-de/kulturpass-documentation#13]
The title says it all. Why does the app check the "Pseudonym", "Gülitg bis" & "Geburtsort" fields of the ID?
I don't see a reason for why you would need this information.

**Comment by thomasaugsten** [comment]
This data is needed to prevent double identification and fraud. Because Name and DOB is not sufficient to identify people.

**Comment by Ein-Tim** [comment]
Okay, thanks!
