### ISSUE TITLE
Change process to open development

### ISSUE THREAD

**Issue by Ein-Tim** [kulturpass-de/kulturpass-documentation#14]
Currently, you are committing the final releases to the GitHub repo but don't actually develop in the open. Please change that as soon as there is enough capacity for the team to change the processes.
You also stated that you will do that here:
> Especially in the early stages of the project the code is still undergoing considerable changes. In order to ensure a timely release of the solution and to be able to concentrate on the initial requirements, the project team decided to focus on the publication of our project milestones instead of every single commit at the moment. In other words, the actual development is currently done on an internal platform. We will switch to the usual public development model as soon as the codebase and architecture is consolidated. 

Taken from: https://github.com/kulturpass-de/kulturpass-documentation/blob/main/CONTRIBUTING.md

**Comment by Ein-Tim** [comment]
@thomasaugsten With the release of version 1.1.0 it seems like the initial & hotfix only phase is over so it seems adequate, at least from the outside, to change the development process.

**Comment by thomasaugsten** [comment]
We still working on a plan to move CI/CD pipeline to the public github. But because of the high effort and very litttle benefit of seeing every commit in github.com we stick with publishing releases.

**Comment by Ein-Tim** [comment]
If that's also the plan for the long-term, you should change the documentation accordingly.

**Comment by Ein-Tim** [comment]
I provided https://github.com/kulturpass-de/kulturpass-documentation/pull/16
