### ISSUE TITLE
Usage of the KulturPass budget in 2024?

### ISSUE THREAD

**Issue by Ein-Tim** [kulturpass-de/kulturpass-documentation#17]
The Usage policy of the KulturPass app says that the budget of the project is only available till 31.12.203: 

> Das Budget kann ab der Aktivierung des Nutzerkontos des Berechtigten Nutzers nur durch diesen selbst, jedoch nicht vor seinem 18. Geburtstag, verwendet werden. **In der Pilotphase des KulturPasses stehen die Mittel grundsätzlich nur bis 31.12.2023 zur Verfügung.** Angebote, die in 2023 reserviert werden und die von der Stiftung Digitale Chancen gegenüber den Kulturanbietern noch in 2023 grundsätzlich erstattet werden, können auch in 2024 wahrgenommen werden. Soweit für die Pilotphase eine Überjährigkeit in 2024 zum Jahresende hergestellt werden kann, können auch noch in 2024 Erstattungszahlungen geleistet werden, sofern die 2023 getätigte Reservierung 2024 wahrgenommen wurde.

Does this mean we will no longer be able to use the KulturPass in 2024?

**Comment by thomasaugsten** [comment]
As things currently stand, you still have until 31 December 2023 to use your budget, as the KulturPass is still in the pilot phase until then.
We are working to continue the KulturPass next year so that you can also use your budget in 2024.

**Comment by Ein-Tim** [comment]
Thanks Thomas! Happy holidays to you and the team!
