### ISSUE TITLE
Contributions on GitHub: Some questions & suggestions

### ISSUE THREAD

**Issue by Ein-Tim** [kulturpass-de/kulturpass-documentation#3]
Hey there, 

firstly, a big thank you for the comprehensive and extensive documentation on the KulturPass DE project! I would love to contribute to this project in my spare time in the future and to ensure that
a) my contributions are on a high level
b) the changes I contribute are welcome
c) contributions are easily understood

I have some questions, suggestions, etc.

### Issue templates

I think it would make sense to add issue templates to both https://github.com/kulturpass-de/kulturpass-documentation and to https://github.com/kulturpass-de/kulturpass-app. 
The issue template used in [this repository](https://github.com/kulturpass-de/kulturpass-documentation) should probably focus on issues with the documentation (first template) and questions on the documentation (second template). A welcome plus would be a template where the community can request, from their POV, missing documentation.
The issue template used in the https://github.com/kulturpass-de/kulturpass-app repository should probably focus on bug reports (first template), enhancement requests (second template), feature requests (third template) and one on questions (fourth template).
I'm not yet sure whether it would be a good decision to further split up the bug reports template in one for UI/UX issues and one for technical problems. Any opinions on that?

To improve the process of creating issues, I recommend using [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) instead of issue templates. This will make it easier for users to fill out the necessary information and provide a more comprehensive overview of the issue.

### Pull request templates

To streamline how contributions are made and to make sure that they all fulfill certain requirements, I think it would be good to use pull request templates. A good template would require a description of the change and, if applicable, references to GitHub issues.
Screenshots are also always a welcome addition, for example if the UI of the app changes.

### Labels

I recommend to use labels, so that issues and pull requests can easily be classified and categorized. 

## My questions

1. Are contributions to the documentation documents already welcome, or should I refrain from providing PRs for this? I'm asking because you are stating that "This documentation is subject of change. We expect the documentation will evolve on a daily basis, especially at the beginning of the project." ([reference](https://github.com/kulturpass-de/kulturpass-documentation#project-documentation-kulturpass-de)). I'm asking to make sure that work is not lost when the documentation is updated.
2. Is the documentation published in this repository the latest one? It was added six weeks ago, so either the expectation that the documentation would evolve on a daily basis didn't become reality or the updated documents were not published.
3. Should I already start opening issues in the app repository for bugs I spot in the app right now or enhancement requests? Or would you first like to release an initial version and then want the community to provide issues?

**Comment by christianneu** [comment]
Hey @Ein-Tim,

Thanks for reaching out. We also thought about the issue templates. I guess it depends somewhat on the general interest on the project and the amount of feedback from the users in order to not overcomplicating things. Let's wait until the app is live and in the meantime I will have a look at it to prepare it.

Sure, contributions are welcome and we are happy if you provide issues/pull requests for it. As we are currently in the final phase of development for the initial release we are currently focusing on getting things ready. But we are also working on the documentation which should be updated soon again. Changes should not be lost, but of course we cannot guarantee it. To summarize it: Feel free to open issues if you find bugs or if you have ideas for enhancements/feature requests. :-)

**Comment by Ein-Tim** [comment]
Thanks Christian sounds good to me!
For you and the team: good luck in the final phase and for go-live!
